--- 
# Create local network bridge for docker
# docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 mynet
appVersion: 1.0.0
server:
  grpc:
   address: :5001
  http:
   address: :80
user:
  ratingsUrl: "http://www.mocky.io/v2/5edbe434320000b5ad5d282f"
  favouritesUrl: ":5001"
